#!/bin/bash
# scripts/install-cron.sh
#
# One-shot installer for the daily 06:00 pipeline cron on macOS.
# Run from any directory:
#   bash <repo>/scripts/install-cron.sh
#
# What it does:
#   1. Creates ~/Library/Application Support/sofiare/ and writes a tiny
#      external entry script there (needed because launchd-spawned bash
#      cannot read scripts inside ~/Downloads on modern macOS, even with
#      Full Disk Access — see commit 70b4bb1 for the gory TCC details).
#   2. Creates ~/Library/Logs/sofiare/ for launchd-side log capture.
#   3. Copies the launchd plist to ~/Library/LaunchAgents/ and loads it.
#   4. Verifies the job is registered.
#
# Prerequisites you must do MANUALLY first:
#   - Grant /bin/bash Full Disk Access:
#       System Settings → Privacy & Security → Full Disk Access → +
#       → ⌘+Shift+G → /bin/bash → toggle ON
#   - Set TELEGRAM_BOT_TOKEN in ~/.zshrc (or .env in the repo root)

set -u
set -o pipefail

# Resolve repo root from this script's location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

EXTERNAL_DIR="$HOME/Library/Application Support/sofiare"
EXTERNAL_SCRIPT="$EXTERNAL_DIR/run-pipeline.sh"
LOG_DIR="$HOME/Library/Logs/sofiare"
PLIST_SRC="$REPO_DIR/scripts/com.sofiare.daily-pipeline.plist"
PLIST_DST="$HOME/Library/LaunchAgents/com.sofiare.daily-pipeline.plist"
INNER_WRAPPER="$REPO_DIR/scripts/run-full-pipeline.sh"

echo "Installing Sofia RE daily cron..."
echo "  Repo:    $REPO_DIR"
echo "  Inner:   $INNER_WRAPPER"
echo "  Entry:   $EXTERNAL_SCRIPT"
echo "  Plist:   $PLIST_DST"
echo

if [ ! -f "$PLIST_SRC" ]; then
    echo "ERROR: launchd plist not found at $PLIST_SRC" >&2
    exit 1
fi
if [ ! -f "$INNER_WRAPPER" ]; then
    echo "ERROR: inner wrapper not found at $INNER_WRAPPER" >&2
    exit 1
fi

mkdir -p "$EXTERNAL_DIR" "$LOG_DIR" "$HOME/Library/LaunchAgents"

# Write the external entry script. Lives outside ~/Downloads so launchd can
# read it without TCC issues. It just exec's into the in-repo wrapper, where
# bash's FDA grant takes effect.
cat > "$EXTERNAL_SCRIPT" <<EOF
#!/bin/bash
# Auto-generated by scripts/install-cron.sh — do not edit by hand.
# External entry point for launchd. Lives outside ~/Downloads to dodge TCC.
set -u
set -o pipefail
INNER_WRAPPER="$INNER_WRAPPER"
if [ ! -f "\$INNER_WRAPPER" ]; then
    echo "ERROR: inner wrapper not found at \$INNER_WRAPPER" >&2
    exit 1
fi
exec /bin/bash "\$INNER_WRAPPER"
EOF
chmod +x "$EXTERNAL_SCRIPT"
echo "✓ Wrote external entry: $EXTERNAL_SCRIPT"

# Patch the plist to point at THIS user's external script path. The committed
# plist hard-codes /Users/kbez/...; if installing on another user, rewrite it.
TMP_PLIST="$(mktemp)"
sed "s|/Users/kbez/Library/Application Support/sofiare/run-pipeline.sh|$EXTERNAL_SCRIPT|g; \
     s|/Users/kbez/Library/Logs/sofiare/launchd-stdout.log|$LOG_DIR/launchd-stdout.log|g; \
     s|/Users/kbez/Library/Logs/sofiare/launchd-stderr.log|$LOG_DIR/launchd-stderr.log|g" \
    "$PLIST_SRC" > "$TMP_PLIST"

# Unload prior version (no-op if missing) then install fresh
launchctl unload "$PLIST_DST" 2>/dev/null || true
cp "$TMP_PLIST" "$PLIST_DST"
rm -f "$TMP_PLIST"
launchctl load -w "$PLIST_DST"
echo "✓ Loaded launchd job: $PLIST_DST"

echo
echo "Verifying registration..."
if launchctl list | grep -q "com.sofiare.daily-pipeline"; then
    echo "✓ Job registered. Will fire daily at 06:00 local time."
else
    echo "✗ Job NOT registered. Check ~/Library/Logs/sofiare/launchd-stderr.log" >&2
    exit 1
fi

echo
echo "DONE."
echo
echo "Test it now (will run the full ~5-30 min pipeline):"
echo "  launchctl start com.sofiare.daily-pipeline"
echo
echo "Watch the log:"
echo "  tail -f \"$REPO_DIR/data/logs/cron-\$(date +%Y-%m-%d).log\""
echo
echo "Uninstall:"
echo "  launchctl unload $PLIST_DST"
echo "  rm $PLIST_DST"
